let enemies = [];
let projectiles = [];

function handleCombatAction(item, base) {
    if (base.isRanged) {
            if (item.ammo > 0) {
                        // Disparar
                                    item.ammo--;
                                                notify(`¡Pum! Quedan ${item.ammo} balas.`);
                                                            // Aquí agregaremos la lógica del proyectil hacia el enemigo más cercano
                                                                    } else {
                                                                                // Recargar
                                                                                            if (countItem('municion') > 0) {
                                                                                                            let needed = base.maxAmmo - item.ammo;
                                                                                                                            let have = countItem('municion');
                                                                                                                                            let toLoad = Math.min(needed, have);
                                                                                                                                                            
                                                                                                                                                                            // Consumir munición del inventario
                                                                                                                                                                                            let rem = toLoad;
                                                                                                                                                                                                            for (let i = game.inv.length - 1; i >= 0; i--) {
                                                                                                                                                                                                                                if (game.inv[i].id === 'municion') {
                                                                                                                                                                                                                                                        let take = Math.min(game.inv[i].qty, rem);
                                                                                                                                                                                                                                                                                removeItem(game.inv[i].uid, take); rem -= take;
                                                                                                                                                                                                                                                                                                        if (rem <= 0) break;
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            item.ammo += toLoad;
                                                                                                                                                                                                                                                                                                                                                                            notify(`Arma recargada. (+${toLoad})`);
                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                        notify("No tienes munición.");
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                        // Ataque melee
                                                                                                                                                                                                                                                                                                                                                                                                                                                notify("Has atacado con " + base.name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        item.dur--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(item.dur <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            removeItem(item.uid, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        notify(base.name + " se ha roto.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderHotbar(); // Actualiza el texto del botón
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function updateCombatBtnText(item, base) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(base.isRanged) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return item.ammo > 0 ? `Disparar (${item.ammo})` : `Recargar`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return base.action;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            